
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_PATHS = "dist/admin/assets/**,public/admin/assets/**,tina/__generated__/**"


# Headers per il CMS admin
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Content-Security-Policy = "connect-src 'self' https://cognito-idp.us-east-1.amazonaws.com https://content.tinajs.io https://identity.tinajs.io https://assets.tinajs.io https://api.tina.io https://*.amazonaws.com https://*.s3.amazonaws.com; img-src 'self' data: https: blob:; form-action 'self' https://content.tinajs.io;"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# Cache control per file di contenuto
[[headers]]
  for = "/src/content/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Redirect per l'admin di TinaCMS (DEVE ESSERE PRIMA DELLA REGOLA GENERICA)
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Redirect generico per il sito (gestisce tutte le altre pagine)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
